modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="create_templates_gears"
version="1.1.0"
displayName="Create: Templates & Gears"
displayURL="https://github.com/JustArthur/create-templates-gears"
logoFile="logo.png"
credits="su apt install Kuma"
authors="su apt install Kuma"
description="Allows you to create Smithing Templates using the machines from the Create mod."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.create_templates_gears]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration